version: "3.8"

services:
  docker-mysql:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=testtimesheetdb
    ports:
      - 3306:3340
    volumes:
      - C:/wamp64/bin/mysql
  app:
    depends_on:
      - docker-mysql
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - 8099:8099
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://docker-mysql:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2 C:/Users/HP/.m2
    stdin_open: true
    tty: true

volumes:
  db: